DROP TABLE IF EXISTS US500;
CREATE TABLE IF NOT EXISTS US500 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS USTECH;
CREATE TABLE IF NOT EXISTS USTECH (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS EU50;
CREATE TABLE IF NOT EXISTS EU50 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS WALL;
CREATE TABLE IF NOT EXISTS WALL (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS DE30;
CREATE TABLE IF NOT EXISTS DE30 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS FT100;
CREATE TABLE IF NOT EXISTS FT100 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS EURUSD;
CREATE TABLE IF NOT EXISTS EURUSD (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GBPUSD;
CREATE TABLE IF NOT EXISTS GBPUSD (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS USDJPY;
CREATE TABLE IF NOT EXISTS USDJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS EURGBP;
CREATE TABLE IF NOT EXISTS EURGBP (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GBPJPY;
CREATE TABLE IF NOT EXISTS GBPJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GBPEUR;
CREATE TABLE IF NOT EXISTS GBPEUR (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS EURJPY;
CREATE TABLE IF NOT EXISTS EURJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS USDTHB;
CREATE TABLE IF NOT EXISTS USDTHB (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS NG;
CREATE TABLE IF NOT EXISTS NG (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS CL;
CREATE TABLE IF NOT EXISTS CL (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS LCO;
CREATE TABLE IF NOT EXISTS LCO (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GC;
CREATE TABLE IF NOT EXISTS GC (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS SI;
CREATE TABLE IF NOT EXISTS SI (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS HG;
CREATE TABLE IF NOT EXISTS HG (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS AAPLUS;
CREATE TABLE IF NOT EXISTS AAPLUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS MSFTUS;
CREATE TABLE IF NOT EXISTS MSFTUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS AMZNUS;
CREATE TABLE IF NOT EXISTS AMZNUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS FBUS;
CREATE TABLE IF NOT EXISTS FBUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS NVDAUS;
CREATE TABLE IF NOT EXISTS NVDAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS TSLAUS;
CREATE TABLE IF NOT EXISTS TSLAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GOOGLUS;
CREATE TABLE IF NOT EXISTS GOOGLUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS GOOGUS;
CREATE TABLE IF NOT EXISTS GOOGUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS COINUS;
CREATE TABLE IF NOT EXISTS COINUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS MARAUS;
CREATE TABLE IF NOT EXISTS MARAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS BABAUS;
CREATE TABLE IF NOT EXISTS BABAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS MSTRUS;
CREATE TABLE IF NOT EXISTS MSTRUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS AMDUS;
CREATE TABLE IF NOT EXISTS AMDUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS RIOTUS;
CREATE TABLE IF NOT EXISTS RIOTUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS PLTRUS;
CREATE TABLE IF NOT EXISTS PLTRUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

DROP TABLE IF EXISTS NFLXUS;
CREATE TABLE IF NOT EXISTS NFLXUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);