CREATE TABLE IF NOT EXISTS US500 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS USTECH (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS EU50 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS WALL (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS DE30 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS FT100 (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS EURUSD (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GBPUSD (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS USDJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS EURGBP (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GBPJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GBPEUR (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS EURJPY (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS USDTHB (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS NG (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS CL (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS LCO (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GC (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS SI (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS HG (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS AAPLUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS MSFTUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS AMZNUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS FBUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS NVDAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS TSLAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GOOGLUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS GOOGUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS COINUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS MARAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS BABAUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS MSTRUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS AMDUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS RIOTUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS PLTRUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS NFLXUS (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS BITCOIN (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);

CREATE TABLE IF NOT EXISTS ETHUSD (unixTime INTEGER PRIMARY KEY, price REAL, longPositionPercentage INTEGER);